name: Build Windows Installer

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: electron/package-lock.json

      - name: Install deps
        working-directory: electron
        run: |
          npm ci || npm install
          npm install --no-audit --no-fund

      - name: Build installer
        working-directory: electron
        run: |
          npm run build
          Get-ChildItem build -Recurse | Select-Object FullName,Length | Format-Table

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            electron/build/*.exe
            electron/build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
